### ISSUE TITLE
Oops! Randomization failed. Please try again with clean files.

### ISSUE THREAD

**Issue by NolanNumbuh1** [rambon99/Fire-Emblem-Awakening-Randomizer#5]
Hi,

I do not know if this github will get any answers to be honest, but I just decided to use this randomizer, but I keep getting the same error over and over. I am using a brand new SD card if this means anything (I am not the best at this type of stuff). Any help would be appreciated.

**Comment by Tuytoooooo** [comment]
Hello
I need help for this same problem (i got the error message "try again with clean files")
Can anyone tell me how it was fixed, please? This is a total begging.
I am new to github, maybe there was a simple way to see how this issue was solved, sorry for the eventual disturbing and my possible blunt behaviour,
Thanks for the understanding
Have a good day, please.

**Comment by rambon99** [comment]
> Hello I need help for this same problem (i got the error message "try again with clean files") Can anyone tell me how it was fixed, please? This is a total begging. I am new to github, maybe there was a simple way to see how this issue was solved, sorry for the eventual disturbing and my possible blunt behaviour, Thanks for the understanding Have a good day, please.

Hi. Make sure you're using the latest version [HERE](https://github.com/rambon99/Fire-Emblem-Awakening-Randomizer/releases/tag/0.7) and not downloading the actual Github repository. It shouldn't give any problems. If there are still problems, I'm not sure what could be causing them to be honest. You would need to give me a more in depth description of what problem you're having. You can also click the checkmark for debug log and send me that file.

**Comment by Tuytoooooo** [comment]
Hi. I have been trying to launch the "OddRhythm.exe"  but it says I need a java runtime environnment. So I did a lot of things for several hours changing settings and following java tutorials to make sure my java runtime environnment file worked, and I only tried the 1.8 version (the latest I think) and I meant to ask, even though I don't want to be annoying, _**what javaRE version do I need to use**_ in order to make this work? I believe it should be one that came out at the same time that java 18, well my question is long, sorry, I thank you for your time.
